config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'retweets/create'
  get 'likes/create'
  get 'tweets/all_tweets'
  post 'likes/:tweet_id', to: 'likes#create', as: 'likes'
  post 'retweets/:tweet_id', to: 'retweets#create', as: 'retweets'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'omniauth'
  }
  post 'api/news'
  post 'api/:fecha1/:fecha2', to: 'api#between_dates' 
  post 'api/create_tweet', to: 'api#create_tweet'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to: "home#index"
  resources :tweets do 
    collection do
      get :searching_tweet
    end
  end
  
  resources :likes
  resources :users
  root 'tweets#index'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :retweets
  validates :content, presence: true
  paginates_per 50

  scope :tweets_for_me, -> (user_ids) {where(user_id: user_ids)}

  def users_images
    user_ids = likes.pluck(:user_id)
    user_images = User.where(id: user_ids).pluck(:image_url)
    user_images
  end

   
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def index
      
    @q = Tweet.ransack(params[:q])
    if user_signed_in?
      @followings = current_user.followings.pluck(:followed_id )
      @tweets = Tweet.tweets_for_me(@followings).order(created_at: :desc).page(params[:page])
      @tweet = Tweet.new
    else 
      @tweets = Tweet.order(created_at: :desc).page(params[:page])
      @tweet = Tweet.new
    end
      
    @tweet = Tweet.new

    @tweets = if params.has_key? :search
                @tweets.where("content LIKE '%#{params[:search]}%'")
              else
                @tweets
              end
  end

  def searching_tweet
    @q = Tweet.ransack(params[:q])
    @tweet_search = @q.result(distinct: true)
  end

  def new
    @tweet = Tweet.new
  end

  def show
    @tweet = Tweet.find(params[:id]) 
  end

  def edit
  end

  def create
    @tweet = Tweet.create(tweet_params)
    @tweet.user = current_user
    
    if @tweet.save
      flash[:notice] = "Tu Tweet ha sido creado"      
    else
      flash[:notice] = "el tweet no se creo"      
    end
    redirect_to "/tweets"
  end

  def update
  end

  def destroy
  end

  def all_tweets
    if user_signed_in?
      @tweets = Tweet.order(created_at: :desc).page(params[:page])
      @tweet = Tweet.new
    else 
      @tweets = Tweet.order(created_at: :desc).page(params[:page])
      @tweet = Tweet.new
    end 
    @tweets = if params.has_key? :search
      @tweets.where("content LIKE '%#{params[:search]}%'")
    else
      @tweets
    end
  end

  private
  

  def tweet_params
    params.require(:tweet).permit(:content, :image_url)
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def render_with_hashtags(content)
    content_words = content.split(" ")
    content_with_links = content_words.map do |word| 
      if word.include?("#")
        link_to word, tweets_path(search: word)
      else
        word
      end
    end

    content_with_links.join(" ")
  end
end

app/views/tweets/_form.html.erb
<%= form_with model: @tweet do |form| %>
  
  <% if @tweet.errors.any? %>
    <h2>Errors:</h2>
    <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= form.label :content, 'Mensaje' %>
    <%= form.text_area :content, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :image_url, "Url de Imagen" %>
    <%= form.text_field :image_url, class: "form-control" %>
  </div>
  <div class= "py-3">
    <%= form.submit "Crear", class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/tweets/all_tweets.html.erb
<h1 class="py-4">Tweets</h1>

<% if current_user %>
  <div>
    <%= render "form" %>
  </div>

  <% @tweets.each do |tweet| %>

    <div class="card my-4" style="width: 18rem;">
      <%= image_tag "#{tweet.image_url}", class: "card-img-top" %>
      <div class="card-body">
        <p class="card-text"><%= render_with_hashtags(tweet.content).html_safe %></p>
        <%= link_to "#{tweet.likes.count} " " Like " , likes_path(tweet.id), method: :post,  class:"btn btn-primary btn-sm" %>
        <%= link_to "#{tweet.retweets.count} " " Re-tweet ", retweets_path(tweet.id), method: :post, class:"btn btn-primary btn-sm" %>
        <%= link_to distance_of_time_in_words(Time.now, tweet.created_at), tweet_path(tweet.id) %>
      </div>
    </div>
  <% end %>


  <% else %>
    <% @tweets.each do |tweet| %>
    <div class="card my-4" style="width: 18rem;">
      <%= image_tag "#{tweet.image_url}", class: "card-img-top"%>
      <div class="card-body">
        <p class="card-text"><%= render_with_hashtags(tweet.content).html_safe %></p>
        <%= link_to "Re-tweet", tweets_path, class:"btn btn-primary btn-sm" %>
        <%= link_to distance_of_time_in_words(Time.now, tweet.created_at), tweet_path(tweet.id) %>
      </div>
    </div>
  <% end %>

<% end %>

<%= paginate @tweets %>

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/destroy.html.erb
<h1>Tweets#destroy</h1>
<p>Find me in app/views/tweets/destroy.html.erb</p>

app/views/tweets/edit.html.erb
<h1>Tweets#edit</h1>
<p>Find me in app/views/tweets/edit.html.erb</p>

app/views/tweets/index.html.erb
<%= search_form_for @q, url:searching_tweet_tweets_path, method: :get, class:"form-inline my-2 my-lg-0" do |f| %>
      <%= f.search_field :content_cont, class:"form-control mr-sm-2" %>
      <%= f.submit "Buscar", class:"btn btn-outline-success my-2 my-sm-0"%>
<% end %>
<h1 class="py-4">Tweets</h1>

<% if current_user %>
  <div>
    <%= render "form" %>
  </div>

  

  <% @tweets.each do |tweet| %>

    <div class="card my-4" style="width: 18rem;">
      <%= image_tag "#{tweet.image_url}", class: "card-img-top" %>
      <div class="card-body">
        <p class="card-text"><%= render_with_hashtags(tweet.content).html_safe %></p>
        <%= link_to "#{tweet.likes.count} " " Like " , likes_path(tweet.id), method: :post,  class:"btn btn-primary btn-sm" %>
        <%= link_to "#{tweet.retweets.count} " " Re-tweet ", retweets_path(tweet.id), method: :post, class:"btn btn-primary btn-sm" %>
        <%= link_to distance_of_time_in_words(Time.now, tweet.created_at), tweet_path(tweet.id) %>
      </div>
    </div>

  <% end %>
  <% else %>
    
      <% @tweets.each do |tweet| %>
        <div class="card my-4" style="width: 18rem;">
          <%= image_tag "#{tweet.image_url}", class: "card-img-top"%>
          <div class="card-body">
            <p class="card-text"><%= tweet.content %></p>
            <%= link_to "Re-tweet", tweets_path, class:"btn btn-primary btn-sm" %>
            <%= link_to distance_of_time_in_words(Time.now, tweet.created_at), tweet_path(tweet.id) %>
          </div>
        </div>
  <% end %>

<% end %>


<%= paginate @tweets %>

app/views/tweets/new.html.erb
<h1 class="pt-4">Nuevo Tweet</h1>

<%= render "form" %>

<div class="btn-group" role="group" aria-label="Basic example">
  <%= link_to "atras", tweets_path, class: "btn btn-secondary" %>
</div>

app/views/tweets/searching_tweet.html.erb
<% @tweet_search.each do |tweet| %>
    <div class="card my-4" style="width: 18rem;">
      <%= image_tag "#{tweet.image_url}", class: "card-img-top" %>
      <div class="card-body">
        <p class="card-text"><%= tweet.content %></p>
        <%= link_to "Like", likes_path(tweet.id), method: :post,  class:"btn btn-primary btn-sm" %>
        <%= link_to "Re-tweet", tweets_path, class:"btn btn-primary btn-sm" %>
        <%= link_to distance_of_time_in_words(Time.now, tweet.created_at), tweet_path(tweet.id) %>
      </div>
    </div>
<% end %>

app/views/tweets/show.html.erb
<h1>Tweet Description</h1>


      <p><%= @tweet.user.username %></p>    
      <p><%= image_tag "#{@tweet.image_url}" %></p>
      <p><%= @tweet.id %></p>
      <p><%= distance_of_time_in_words(Time.now, @tweet.created_at) %></p>
      <p><%=image_tag "#{@tweet.user.image_url}", class:"image-icon" %></p>

      <div>
            <% @tweet.users_images.each do |tw| %>
                   <%=image_tag "#{tw}" %>
            <% end %>
      </div>

app/views/tweets/update.html.erb
<h1>Tweets#update</h1>
<p>Find me in app/views/tweets/update.html.erb</p>