config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'retweets/create'
  get 'likes/create'
  get 'tweets/all_tweets'
  post 'likes/:tweet_id', to: 'likes#create', as: 'likes'
  post 'retweets/:tweet_id', to: 'retweets#create', as: 'retweets'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'omniauth'
  }
  post 'api/news'
  post 'api/:fecha1/:fecha2', to: 'api#between_dates' 
  post 'api/create_tweet', to: 'api#create_tweet'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to: "home#index"
  resources :tweets do 
    collection do
      get :searching_tweet
    end
  end
  
  resources :likes
  resources :users
  root 'tweets#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/retweet.rb
class Retweet < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :retweets
  validates :content, presence: true
  paginates_per 50

  scope :tweets_for_me, -> (user_ids) {where(user_id: user_ids)}

  def users_images
    user_ids = likes.pluck(:user_id)
    user_images = User.where(id: user_ids).pluck(:image_url)
    user_images
  end

   
  
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_token_authenticatable
  
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :retweets, dependent: :destroy
  has_many :active_relationships,  class_name:  "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name:  "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end    
end

app/controllers/api_controller.rb
class ApiController < ActionController::API
  acts_as_token_authentication_handler_for User

  def news
    @tweets = Tweet.all.order(created_at: :desc).page(params[:page])
    @tweets = @tweets.map do |tweet|
                {
                  id: tweet.id,
                  content: tweet.content,
                  user_id: tweet.user_id,
                  likes_count: tweet.likes.count,
                  retweets_count: tweet.retweets.count,
                }
    end
    render json: @tweets
  end

  def between_dates
    @tweets = Tweet.where(created_at: date1..date2)
    @tweets = @tweets.map do |tweet|
      {
        id: tweet.id,
        content: tweet.content,
        user_id: tweet.user_id,
        likes_count: tweet.likes.count,
        retweets_count: tweet.retweets.count,
        date: tweet.created_at
      }
    end
    render json: @tweets
  end

  def create_tweet
    @tweet = Tweet.create(
      content: params.require(:content),
      user: current_user
    )
    
    render json: @tweet
  end


  
  private
  def date1
    params[:fecha1].to_date.beginning_of_day
  end

  def date2
    params[:fecha2].to_date.end_of_day
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @like = Like.find_by(user_id: current_user.id, tweet_id: params[:tweet_id])
    if @like && @like.active
      @like.update_attribute(:active, 'false')
      @like.destroy
    elsif @like && !@like.active
      @like.update_attribute(:active, 'true')
      
    else
      @like = Like.create(user_id: current_user.id, tweet_id: params[:tweet_id])
    end  
    redirect_to root_path
  end

  
end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController
skip_before_action :verify_authenticity_token

  def google_oauth2
    @user = User.create_from_provider_data(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user
    else
      flash[:error] = 'There was a problem signing you'
      redirect_to new_user_registration_url
    end
  end
  
  def failure
    flash[:error] = "There was a problem signin you in."
    redirect_to new_user_registration_path
  end
end

app/controllers/retweets_controller.rb
class RetweetsController < ApplicationController
  before_action :authenticate_user!

  def create
      @retweet = Retweet.find_by(user_id: current_user.id, tweet_id: params[:tweet_id])
      if @retweet && @retweet.active
        @retweet.update_attribute(:active, 'false')
        @retweet.destroy
      elsif @retweet && !@retweet.active
        @retweet.update_attribute(:active, 'true')
        
      else
        @retweet = Retweet.create(user_id: current_user.id, tweet_id: params[:tweet_id])
      end  
      redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def index
      
    @q = Tweet.ransack(params[:q])
    if user_signed_in?
      @followings = current_user.followings.pluck(:followed_id )
      @tweets = Tweet.tweets_for_me(@followings).order(created_at: :desc).page(params[:page])
      @tweet = Tweet.new
    else 
      @tweets = Tweet.order(created_at: :desc).page(params[:page])
      @tweet = Tweet.new
    end
      
    @tweet = Tweet.new

    @tweets = if params.has_key? :search
                @tweets.where("content LIKE '%#{params[:search]}%'")
              else
                @tweets
              end
  end

  def searching_tweet
    @q = Tweet.ransack(params[:q])
    @tweet_search = @q.result(distinct: true)
  end

  def new
    @tweet = Tweet.new
  end

  def show
    @tweet = Tweet.find(params[:id]) 
  end

  def edit
  end

  def create
    @tweet = Tweet.create(tweet_params)
    @tweet.user = current_user
    
    if @tweet.save
      flash[:notice] = "Tu Tweet ha sido creado"      
    else
      flash[:notice] = "el tweet no se creo"      
    end
    redirect_to "/tweets"
  end

  def update
  end

  def destroy
  end

  def all_tweets
    if user_signed_in?
      @tweets = Tweet.order(created_at: :desc).page(params[:page])
      @tweet = Tweet.new
    else 
      @tweets = Tweet.order(created_at: :desc).page(params[:page])
      @tweet = Tweet.new
    end 
    @tweets = if params.has_key? :search
      @tweets.where("content LIKE '%#{params[:search]}%'")
    else
      @tweets
    end
  end

  private
  

  def tweet_params
    params.require(:tweet).permit(:content, :image_url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end
  
  def update
  end

  def destroy
  end

  def show
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/retweets_helper.rb
module RetweetsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def render_with_hashtags(content)
    content_words = content.split(" ")
    content_with_links = content_words.map do |word| 
      if word.include?("#")
        link_to word, tweets_path(search: word)
      else
        word
      end
    end

    content_with_links.join(" ")
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>TwitterClon</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
  </script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render "shared/navbar" %>  

  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert<%= key %>"><%= value %></div>
    <% end %>
  <%= yield %>
  </div>

</body>

</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"></a>
  
   
  
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <% if signed_in? %>
        <%= link_to "Inicio", tweets_path, class: "nav-item nav-link" %>
        <%= link_to "Crear tweet", new_tweet_path, class: "nav-item nav-link" %>
        <%= link_to "Todos los tweets", tweets_all_tweets_path, class: "nav-item nav-link" %>
        <%= link_to "Perfil", edit_user_registration_path, class: "nav-item nav-link" %>
        <%= link_to "Salir", destroy_user_session_path, method: :delete, data: { confirm: 'Estas seguro?'}, class: "nav-item nav-link" %>
        
      <% else %>
        <%= link_to "Inicio", tweets_path, class: "nav-item nav-link" %> 
        <%= link_to "Iniciar sesión", new_user_session_path, class: "nav-item nav-link" %>
         <%= link_to "Registrarse", new_user_registration_path, class: "nav-item nav-link" %>
         <%= link_to "Todos los tweets", tweets_all_tweets_path, class: "nav-item nav-link" %>
      <% end %>
    </div>
    
    
  </div>
  
</nav>